[project]
name = "recipe-box"
authors = [{ name = "Sayantan Santra", email = "sayantan.santra689@gmail.com" }]
license = "MIT"
classifiers = ["Programming Language :: Python :: 3"]
version = "1.0.0"
description = "Download recipes into a (repurposed Zettelkasten) recipe box"
readme = "README.md"
keywords = ["recipe", "food", "recipe-box"]
requires-python = ">=3.8"
dependencies = ["recipe-scrapers", "requests", "httpx[http2]"]
